export const projects = [
  {
    name: "Twitter Clone",
    type: "Full Stack",
    desc: "Simple Twitter Clone where user can log in as one of the Superheroes, post tweets, reply, retweet, like other tweets.",
    stack:
      "Next.js, DjangoRestFramework, PostgreSQL, TailwindCSS, ReactQuery, JWTAuthentication.",
    img: "/assets/twitter-clone.png",
    git: "https://github.com/m-nowak/twitter-clone",
    eye: "https://twitter-clone-frontend-theta.vercel.app",
    eye_title: "",
  },
  {
    name: "Real-time Chat",
    type: "Full Stack",
    desc: "MERN Stack application which allows users to send messages in real-time and receive them instantly.",
    stack: "ReactJs, NodeJs, MongoDB, ExpressJs, SocketIO, ChakraUI",
    img: "/assets/chat-app.png",
    git: "https://github.com/m-nowak/chat-app",
    eye: "https://chat-app-frontend-6y8l.onrender.com",
    eye_title: "",
  },
  {
    name: "Logistic Regression",
    type: "Machine Learning",
    desc: "Machine learning model that will help predict which customers will stop buying service of marketing agency.",
    stack: "Python, JupyterNotebook, PySpark, LogisticRegression",
    img: "/assets/logistic-regression-1.png",
    git: "https://github.com/m-nowak/logistic-regression-2",
    eye: "assets/Logistic-Regression.html",
    eye_title: "HTML page",
  },

  {
    name: "Google Clone",
    type: "Frontend",
    desc: " Completely responsive Google Clone with a modern UI and the ability to search for up-to-date results, news.",
    stack: "Next.js, TypeScript, TailwindCSS, ReactQuery, googleapis.com-API",
    img: "/assets/google-clone.png",
    git: "https://github.com/m-nowak/google-clone",
    eye: "https://google-clone-taupe-kappa.vercel.app",
    eye_title: "",
  },

  {
    name: "Linear Regression",
    type: "Machine Learning",
    desc: "Machine learning model that will help to decide whether to focus on mobile or web app experience of e-commerce company.",
    stack:
      "Python, JupyterNotebook, NumPy, Pandas, Matplotlib, Seaborn, SciKitLearn",
    img: "/assets/linear-regression-1.png",
    git: "https://github.com/m-nowak/linear-regression",
    eye: "/assets/Linear-Regression.html",
    eye_title: "HTML page ",
  },
  {
    name: "Netflix Clone",
    type: "Full Stack",
    desc: " Web application where user can read movie description, watch trailer and create own favorite movie list.",
    stack: "Next.js, TypeScript, TailwindCSS, ReactQuery, Prisma, PostgreSQL.",
    img: "/assets/netflix-clone.png",
    git: "https://github.com/m-nowak/netflix-clone",
    eye: "https://n-c-ten-amber.vercel.app",
    eye_title: "",
  },
];
